import { MenuSectionData } from './types';

export const menuData: MenuSectionData[] = [
  {
    id: 'tex-mex',
    title: 'TEX MEX',
    type: 'standard',
    items: [
      { name: 'Frite', price: 10.0 },
      { name: 'Nugget x 6', price: 20.0 },
      { name: 'Chicken x 2', price: 15.0 },
      { name: 'Chicken x 3', price: 20.0 },
    ],
  },
  {
    id: 'jus',
    title: 'JUS',
    type: 'standard',
    items: [
      { name: 'Banane', price: 15.0 },
      { name: 'Pomme', price: 15.0 },
      { name: 'Orange', price: 15.0 },
      { name: 'Citron', price: 15.0 },
      { name: 'Fraise', price: 18.0 },
      { name: 'Mangue', price: 18.0 },
      { name: 'Papay', price: 18.0 },
      { name: 'Avocat', price: 20.0 },
      { name: 'Ananas', price: 18.0 },
      { name: 'Panache', price: 20.0 },
    ],
  },
  {
    id: 'desserts',
    title: 'DESSERTS',
    type: 'standard',
    items: [{ name: 'Tiramisu', price: 16.0 }],
  },
  {
    id: 'boissons',
    title: 'BOISSONS',
    type: 'standard',
    items: [
      { name: 'Eau Minerale Petit', price: 4.0 },
      { name: 'Soda', price: 6.0 },
      { name: 'Tropical Soda', price: 7.0 },
    ],
  },
  {
    id: 'salades',
    title: 'SALADES',
    type: 'standard',
    items: [
      { name: 'Salade Mexicain', price: 25.0 },
      { name: 'Salade Nicoise', price: 25.0 },
      { name: 'Salade Sniptaste', price: 40.0 },
    ],
  },
  {
    id: 'pizza',
    title: 'PIZZA',
    type: 'dual-price',
    note: 'Supplément Fromage: 10 DH',
    supplements: [{ name: 'Supplément Fromage', price: 10.0 }],
    items: [
      { name: 'Pizza Margherita', prices: { small: 20.0, large: 30.0 } },
      { name: 'Pizza Hot Dog', prices: { small: 25.0, large: 35.0 } },
      { name: 'Pizza Végétarien', prices: { small: 30.0, large: 35.0 } },
      { name: 'Pizza Thon', prices: { small: 30.0, large: 40.0 } },
      { name: 'Pizza Jambon', prices: { small: 30.0, large: 40.0 } },
      { name: 'Pizza Poulet', prices: { small: 30.0, large: 40.0 } },
      { name: 'Pizza Viande Hachée', prices: { small: 30.0, large: 40.0 } },
      { name: 'Pizza Quatre Fromage', prices: { small: 30.0, large: 40.0 } },
      { name: 'Pizza Jasmine', prices: { small: 35.0, large: 45.0 } },
      { name: 'Pizza Milano', prices: { small: 35.0, large: 45.0 } },
      { name: 'Pizza Fruit De Mer', prices: { small: 35.0, large: 45.0 } },
      { name: 'Pizza Pepperoni', prices: { small: 35.0, large: 45.0 } },
      { name: 'Pizza Quatre Saisons', prices: { small: 35.0, large: 45.0 } },
      { name: 'Pizza Sniptaste', prices: { small: 40.0, large: 50.0 } },
    ],
  },
  {
    id: 'burger',
    title: 'BURGER',
    type: 'standard',
    items: [
      { name: 'Chesse Burger', price: 30.0 },
      { name: 'Chicken Burger', price: 30.0 },
      { name: 'Egg Burger', price: 35.0 },
      { name: 'Double Burger', price: 37.0 },
      { name: 'Snip Taste Burger', price: 60.0 },
    ],
  },
  {
    id: 'pasticcios',
    title: 'PASTICCIOS',
    type: 'standard',
    items: [
      { name: 'Pasticcio Viande Hachée', price: 30.0 },
      { name: 'Pasticcio Poulet', price: 30.0 },
      { name: 'Pasticcio Jambon De Dinde Fumée', price: 30.0 },
      { name: 'Pasticcio Mixte', price: 35.0 },
    ],
  },
  {
    id: 'pates',
    title: 'PATES',
    type: 'standard',
    note: 'Supplément Pates : 20DH',
    supplements: [{ name: 'Supplément Pates', price: 20.0 }],
    items: [
      { name: 'Carbonara', price: 30.0 },
      { name: 'Poulet Champignon', price: 30.0 },
      { name: 'Bolognaise', price: 35.0 },
      { name: 'Fruits De Mer', price: 35.0 },
    ],
  },
  {
    id: 'panizzas',
    title: 'PANIZZAS',
    type: 'standard',
    note: 'Avec Frites: +5DH',
    supplements: [{ name: 'Avec Frites', price: 5.0 }],
    items: [
      { name: 'Panizza Hot Dog', price: 30.0 },
      { name: 'Panizza Thon', price: 30.0 },
      { name: 'Panizza Poulet', price: 30.0 },
      { name: 'Panizza Viande Hachée', price: 35.0 },
      { name: 'Panizza Cordon Bleu', price: 35.0 },
      { name: 'Panizza Poulet Pané', price: 35.0 },
    ],
  },
  {
    id: 'tacos',
    title: 'TACOS',
    type: 'standard',
    note: 'Avec Frites | Supp. Fromage: 5DH | Sauce: 2DH',
    supplements: [
      { name: 'Supplément Fromage', price: 5.0 },
      { name: 'Sauce', price: 2.0 },
    ],
    items: [
      { name: 'Tacos Hot Dog', price: 25.0 },
      { name: 'Tacos Poulet', price: 30.0 },
      { name: 'Tacos Chicken', price: 35.0 },
      { name: 'Tacos Nuggets', price: 30.0 },
      { name: 'Tacos Cordon Bleu', price: 35.0 },
      { name: 'Tacos Viand Hachée', price: 33.0 },
      { name: 'Tacos Mixte', price: 35.0 },
      { name: 'Tacos Fruit De Mer', price: 45.0 },
      { name: 'Tacos XL', price: 50.0 },
    ],
  },
  {
    id: 'sandwich',
    title: 'SANDWICH',
    type: 'standard',
    items: [
      { name: 'Sandwich Thon', price: 25.0 },
      { name: 'Sandwich Poulet Americain', price: 35.0 },
      { name: 'Sandwich Viande Hachée Americain', price: 33.0 },
      { name: 'Sandwich Mixte', price: 35.0 },
    ],
  },
  {
    id: 'kabab',
    title: 'KABAB',
    type: 'standard',
    note: 'Sauce: 2DH',
    supplements: [{ name: 'Sauce', price: 2.0 }],
    items: [
      { name: 'Kabab Viande Hachée', price: 30.0 },
      { name: 'Kabab Poulet', price: 30.0 },
      { name: 'Kabab Nuggets', price: 30.0 },
      { name: 'Kabab Cordon Bleu', price: 30.0 },
      { name: 'Kabab Chicken', price: 30.0 },
      { name: 'Kabab Mixte', price: 35.0 },
      { name: 'Kabab Sniptaste', price: 40.0 },
    ],
  },
  {
    id: 'plats',
    title: 'PLATS',
    type: 'standard',
    items: [
      { name: 'Emincé De Poulet', price: 45.0 },
      { name: 'Brochette Poulet', price: 40.0 },
      { name: 'Plat Chicken (Sans Légumes)', price: 40.0 },
      { name: 'Plat Chicken (Avec Légumes)', price: 45.0 },
      { name: 'Brochette Viande Hachée', price: 45.0 },
      { name: 'Plat Mixte', price: 50.0 },
    ],
  },
];
